
-- Country Data
insert into country (code,name) values ('AD','Andorra');
insert into country (code,name) values ('AE','United Arab Emirates');
insert into country (code,name) values ('AF','Afghanistan');
insert into country (code,name) values ('AG','Antigua and Barbuda');
insert into country (code,name) values ('AI','Anguilla');
insert into country (code,name) values ('AL','Albania');
insert into country (code,name) values ('AM','Armenia');
insert into country (code,name) values ('AO','Angola');
insert into country (code,name) values ('AQ','Antarctica');
insert into country (code,name) values ('AR','Argentina');
insert into country (code,name) values ('AS','American Samoa');
insert into country (code,name) values ('AT','Austria');
insert into country (code,name) values ('AU','Australia');
insert into country (code,name) values ('AW','Aruba');
insert into country (code,name) values ('AX','Åland Islands');
insert into country (code,name) values ('AZ','Azerbaijan');
insert into country (code,name) values ('BA','Bosnia and Herzegovina');
insert into country (code,name) values ('BB','Barbados');
insert into country (code,name) values ('BD','Bangladesh');
insert into country (code,name) values ('BE','Belgium');
insert into country (code,name) values ('BF','Burkina Faso');
insert into country (code,name) values ('BG','Bulgaria');
insert into country (code,name) values ('BH','Bahrain');
insert into country (code,name) values ('BI','Burundi');
insert into country (code,name) values ('BJ','Benin');
insert into country (code,name) values ('BL','Saint Barthélemy');
insert into country (code,name) values ('BM','Bermuda');
insert into country (code,name) values ('BN','Brunei Darussalam');
insert into country (code,name) values ('BO','Bolivia');
insert into country (code,name) values ('BQ','Caribbean Netherlands');
insert into country (code,name) values ('BR','Brazil');
insert into country (code,name) values ('BS','Bahamas');
insert into country (code,name) values ('BT','Bhutan');
insert into country (code,name) values ('BV','Bouvet Island');
insert into country (code,name) values ('BW','Botswana');
insert into country (code,name) values ('BY','Belarus');
insert into country (code,name) values ('BZ','Belize');
insert into country (code,name) values ('CA','Canada');
insert into country (code,name) values ('CC','Cocos (Keeling) Islands');
insert into country (code,name) values ('CD','"Congo');
insert into country (code,name) values ('CF','Central African Republic');
insert into country (code,name) values ('CG','Congo');
insert into country (code,name) values ('CH','Switzerland');
insert into country (code,name) values ('CK','Cook Islands');
insert into country (code,name) values ('CL','Chile');
insert into country (code,name) values ('CM','Cameroon');
insert into country (code,name) values ('CN','China');
insert into country (code,name) values ('CO','Colombia');
insert into country (code,name) values ('CR','Costa Rica');
insert into country (code,name) values ('CU','Cuba');
insert into country (code,name) values ('CV','Cape Verde');
insert into country (code,name) values ('CW','Curaçao');
insert into country (code,name) values ('CX','Christmas Island');
insert into country (code,name) values ('CY','Cyprus');
insert into country (code,name) values ('CZ','Czech Republic');
insert into country (code,name) values ('DE','Germany');
insert into country (code,name) values ('DJ','Djibouti');
insert into country (code,name) values ('DK','Denmark');
insert into country (code,name) values ('DM','Dominica');
insert into country (code,name) values ('DO','Dominican Republic');
insert into country (code,name) values ('DZ','Algeria');
insert into country (code,name) values ('EC','Ecuador');
insert into country (code,name) values ('EE','Estonia');
insert into country (code,name) values ('EG','Egypt');
insert into country (code,name) values ('EH','Western Sahara');
insert into country (code,name) values ('ER','Eritrea');
insert into country (code,name) values ('ES','Spain');
insert into country (code,name) values ('ET','Ethiopia');
insert into country (code,name) values ('FI','Finland');
insert into country (code,name) values ('FJ','Fiji');
insert into country (code,name) values ('FK','Falkland Islands');
insert into country (code,name) values ('FM','"Micronesia');
insert into country (code,name) values ('FO','Faroe Islands');
insert into country (code,name) values ('FR','France');
insert into country (code,name) values ('GA','Gabon');
insert into country (code,name) values ('GB','United Kingdom');
insert into country (code,name) values ('GD','Grenada');
insert into country (code,name) values ('GE','Georgia');
insert into country (code,name) values ('GF','French Guiana');
insert into country (code,name) values ('GG','Guernsey');
insert into country (code,name) values ('GH','Ghana');
insert into country (code,name) values ('GI','Gibraltar');
insert into country (code,name) values ('GL','Greenland');
insert into country (code,name) values ('GM','Gambia');
insert into country (code,name) values ('GN','Guinea');
insert into country (code,name) values ('GP','Guadeloupe');
insert into country (code,name) values ('GQ','Equatorial Guinea');
insert into country (code,name) values ('GR','Greece');
insert into country (code,name) values ('GS','South Georgia and the South Sandwich Islands');
insert into country (code,name) values ('GT','Guatemala');
insert into country (code,name) values ('GU','Guam');
insert into country (code,name) values ('GW','Guinea-Bissau');
insert into country (code,name) values ('GY','Guyana');
insert into country (code,name) values ('HK','Hong Kong');
insert into country (code,name) values ('HM','Heard and McDonald Islands');
insert into country (code,name) values ('HN','Honduras');
insert into country (code,name) values ('HR','Croatia');
insert into country (code,name) values ('HT','Haiti');
insert into country (code,name) values ('HU','Hungary');
insert into country (code,name) values ('ID','Indonesia');
insert into country (code,name) values ('IE','Ireland');
insert into country (code,name) values ('IL','Israel');
insert into country (code,name) values ('IM','Isle of Man');
insert into country (code,name) values ('IN','India');
insert into country (code,name) values ('IO','British Indian Ocean Territory');
insert into country (code,name) values ('IQ','Iraq');
insert into country (code,name) values ('IR','Iran');
insert into country (code,name) values ('IS','Iceland');
insert into country (code,name) values ('IT','Italy');
insert into country (code,name) values ('JE','Jersey');
insert into country (code,name) values ('JM','Jamaica');
insert into country (code,name) values ('JO','Jordan');
insert into country (code,name) values ('JP','Japan');
insert into country (code,name) values ('KE','Kenya');
insert into country (code,name) values ('KG','Kyrgyzstan');
insert into country (code,name) values ('KH','Cambodia');
insert into country (code,name) values ('KI','Kiribati');
insert into country (code,name) values ('KM','Comoros');
insert into country (code,name) values ('KN','Saint Kitts and Nevis');
insert into country (code,name) values ('KP','North Korea');
insert into country (code,name) values ('KR','South Korea');
insert into country (code,name) values ('KW','Kuwait');
insert into country (code,name) values ('KY','Cayman Islands');
insert into country (code,name) values ('KZ','Kazakhstan');
insert into country (code,name) values ('LB','Lebanon');
insert into country (code,name) values ('LC','Saint Lucia');
insert into country (code,name) values ('LI','Liechtenstein');
insert into country (code,name) values ('LK','Sri Lanka');
insert into country (code,name) values ('LR','Liberia');
insert into country (code,name) values ('LS','Lesotho');
insert into country (code,name) values ('LT','Lithuania');
insert into country (code,name) values ('LU','Luxembourg');
insert into country (code,name) values ('LV','Latvia');
insert into country (code,name) values ('LY','Libya');
insert into country (code,name) values ('MA','Morocco');
insert into country (code,name) values ('MC','Monaco');
insert into country (code,name) values ('MD','Moldova');
insert into country (code,name) values ('ME','Montenegro');
insert into country (code,name) values ('MF','Saint-Martin (France)');
insert into country (code,name) values ('MG','Madagascar');
insert into country (code,name) values ('MH','Marshall Islands');
insert into country (code,name) values ('MK','Macedonia');
insert into country (code,name) values ('ML','Mali');
insert into country (code,name) values ('MM','Myanmar');
insert into country (code,name) values ('MN','Mongolia');
insert into country (code,name) values ('MO','Macau');
insert into country (code,name) values ('MP','Northern Mariana Islands');
insert into country (code,name) values ('MQ','Martinique');
insert into country (code,name) values ('MR','Mauritania');
insert into country (code,name) values ('MS','Montserrat');
insert into country (code,name) values ('MT','Malta');
insert into country (code,name) values ('MU','Mauritius');
insert into country (code,name) values ('MV','Maldives');
insert into country (code,name) values ('MW','Malawi');
insert into country (code,name) values ('MX','Mexico');
insert into country (code,name) values ('MY','Malaysia');
insert into country (code,name) values ('MZ','Mozambique');
insert into country (code,name) values ('NA','Namibia');
insert into country (code,name) values ('NC','New Caledonia');
insert into country (code,name) values ('NE','Niger');
insert into country (code,name) values ('NF','Norfolk Island');
insert into country (code,name) values ('NG','Nigeria');
insert into country (code,name) values ('NI','Nicaragua');
insert into country (code,name) values ('NL','The Netherlands');
insert into country (code,name) values ('NO','Norway');
insert into country (code,name) values ('NP','Nepal');
insert into country (code,name) values ('NR','Nauru');
insert into country (code,name) values ('NU','Niue');
insert into country (code,name) values ('NZ','New Zealand');
insert into country (code,name) values ('OM','Oman');
insert into country (code,name) values ('PA','Panama');
insert into country (code,name) values ('PE','Peru');
insert into country (code,name) values ('PF','French Polynesia');
insert into country (code,name) values ('PG','Papua New Guinea');
insert into country (code,name) values ('PH','Philippines');
insert into country (code,name) values ('PK','Pakistan');
insert into country (code,name) values ('PL','Poland');
insert into country (code,name) values ('PM','St. Pierre and Miquelon');
insert into country (code,name) values ('PN','Pitcairn');
insert into country (code,name) values ('PR','Puerto Rico');
insert into country (code,name) values ('PS','"Palestine');
insert into country (code,name) values ('PT','Portugal');
insert into country (code,name) values ('PW','Palau');
insert into country (code,name) values ('PY','Paraguay');
insert into country (code,name) values ('QA','Qatar');
insert into country (code,name) values ('RE','Réunion');
insert into country (code,name) values ('RO','Romania');
insert into country (code,name) values ('RS','Serbia');
insert into country (code,name) values ('RU','Russian Federation');
insert into country (code,name) values ('RW','Rwanda');
insert into country (code,name) values ('SA','Saudi Arabia');
insert into country (code,name) values ('SB','Solomon Islands');
insert into country (code,name) values ('SC','Seychelles');
insert into country (code,name) values ('SD','Sudan');
insert into country (code,name) values ('SE','Sweden');
insert into country (code,name) values ('SG','Singapore');
insert into country (code,name) values ('SH','Saint Helena');
insert into country (code,name) values ('SI','Slovenia');
insert into country (code,name) values ('SJ','Svalbard and Jan Mayen Islands');
insert into country (code,name) values ('SK','Slovakia');
insert into country (code,name) values ('SL','Sierra Leone');
insert into country (code,name) values ('SM','San Marino');
insert into country (code,name) values ('SN','Senegal');
insert into country (code,name) values ('SO','Somalia');
insert into country (code,name) values ('SR','Suriname');
insert into country (code,name) values ('SS','South Sudan');
insert into country (code,name) values ('ST','Sao Tome and Principe');
insert into country (code,name) values ('SV','El Salvador');
insert into country (code,name) values ('SX','Sint Maarten (Dutch part)');
insert into country (code,name) values ('SY','Syria');
insert into country (code,name) values ('SZ','Swaziland');
insert into country (code,name) values ('TC','Turks and Caicos Islands');
insert into country (code,name) values ('TD','Chad');
insert into country (code,name) values ('TF','French Southern Territories');
insert into country (code,name) values ('TG','Togo');
insert into country (code,name) values ('TH','Thailand');
insert into country (code,name) values ('TJ','Tajikistan');
insert into country (code,name) values ('TK','Tokelau');
insert into country (code,name) values ('TL','Timor-Leste');
insert into country (code,name) values ('TM','Turkmenistan');
insert into country (code,name) values ('TN','Tunisia');
insert into country (code,name) values ('TO','Tonga');
insert into country (code,name) values ('TR','Turkey');
insert into country (code,name) values ('TT','Trinidad and Tobago');
insert into country (code,name) values ('TV','Tuvalu');
insert into country (code,name) values ('TW','Taiwan');
insert into country (code,name) values ('TZ','Tanzania');
insert into country (code,name) values ('UA','Ukraine');
insert into country (code,name) values ('UG','Uganda');
insert into country (code,name) values ('UM','United States Minor Outlying Islands');
insert into country (code,name) values ('US','United States');
insert into country (code,name) values ('UY','Uruguay');
insert into country (code,name) values ('UZ','Uzbekistan');
insert into country (code,name) values ('VA','Vatican');
insert into country (code,name) values ('VC','Saint Vincent and the Grenadines');
insert into country (code,name) values ('VE','Venezuela');
insert into country (code,name) values ('VG','Virgin Islands (British)');
insert into country (code,name) values ('VI','Virgin Islands (U.S.)');
insert into country (code,name) values ('VN','Vietnam');
insert into country (code,name) values ('VU','Vanuatu');
insert into country (code,name) values ('WF','Wallis and Futuna Islands');
insert into country (code,name) values ('WS','Samoa');
insert into country (code,name) values ('YE','Yemen');
insert into country (code,name) values ('YT','Mayotte');
insert into country (code,name) values ('ZA','South Africa');
insert into country (code,name) values ('ZM','Zambia');
insert into country (code,name) values ('ZW','Zimbabwe');

-- Customer Data
INSERT INTO customer (name,age,country) VALUES ('Jared Mccall',26,210),('Regina Hardy',30,91),('Samantha Ellis',41,226),('Dale Rodgers',31,52),('Leslie Barr',28,236),('Ingrid Fisher',48,90),('Nicholas Bradley',31,189),('Chanda Woodward',33,50),('Wang Miles',42,212),('Ross Silva',34,200);
INSERT INTO customer (name,age,country) VALUES ('Fallon Gilliam',49,205),('Ezekiel Floyd',44,151),('Ignatius Holman',38,50),('Charles Chang',21,220),('Bo Hewitt',46,25),('Ignatius Aguilar',43,192),('Imelda Montoya',49,141),('Brennan Leon',20,96),('Stacey Kline',20,81),('Macy Sampson',50,150);
INSERT INTO customer (name,age,country) VALUES ('Malcolm Mcguire',42,3),('Dane Leach',28,189),('Heidi Mcguire',28,176),('Candace Velez',38,2),('Renee Wood',46,195),('Jessamine Workman',23,191),('Mohammad Carson',38,114),('Axel Bruce',30,195),('Janna Medina',48,83),('Zeph Larsen',30,160);
INSERT INTO customer (name,age,country) VALUES ('Dominic Norris',25,143),('Paki Hardin',23,222),('Boris Palmer',31,166),('Amelia Hayden',38,3),('Tallulah Haley',36,163),('Sacha Baird',32,69),('Ursa Holt',27,118),('Kareem Nguyen',31,50),('Felix Walter',20,38),('Dillon Yang',35,230);
INSERT INTO customer (name,age,country) VALUES ('Deirdre Short',36,219),('Lawrence Lewis',32,145),('Jane Gregory',27,42),('Alan Chandler',20,65),('Uta Hammond',26,25),('Finn Wise',40,91),('Gemma Nelson',23,210),('Oleg Contreras',22,18),('Phoebe Sosa',45,85),('Shea Sears',20,92);
INSERT INTO customer (name,age,country) VALUES ('Blaine Mueller',23,119),('Summer Page',40,39),('Deacon Parks',48,66),('Mariam Hood',46,34),('Chava Lowe',45,83),('Caldwell Rivers',29,126),('Abel Dunn',36,121),('Calista Franco',49,36),('Elizabeth Miranda',42,101),('Lilah Waller',26,234);
INSERT INTO customer (name,age,country) VALUES ('Zorita Austin',35,195),('Vielka William',45,75),('Connor Lambert',27,71),('Jack Barr',38,197),('Jasmine Gaines',24,131),('Giacomo French',24,8),('Wanda Rivas',44,209),('Zeph Murray',46,116),('Aretha Alexander',44,157),('Hannah Moreno',49,74);
INSERT INTO customer (name,age,country) VALUES ('Orlando Salinas',43,234),('Violet Kerr',20,108),('Sade Shepard',38,187),('Garth Atkins',21,147),('Upton Beasley',32,167),('Selma Bright',21,52),('Armand Torres',43,5),('Charlotte Herman',38,35),('Kyla Shepard',30,201),('Michelle Sherman',49,66);
INSERT INTO customer (name,age,country) VALUES ('Cherokee Conway',29,134),('Vivian George',34,48),('Gannon Rasmussen',45,85),('Cailin Hale',41,37),('Timon Gates',50,79),('Mia Bonner',43,13),('Suki Ramos',22,48),('Violet Evans',33,32),('Jessamine Eaton',32,205),('Kirby Hubbard',49,62);
INSERT INTO customer (name,age,country) VALUES ('Lois Shields',36,88),('Kathleen Frazier',36,14),('Jermaine Holmes',39,146),('Brennan Levine',26,150),('Kaitlin Hale',37,14),('Mollie Stone',22,20),('Candice Howe',28,92),('Medge Hunter',42,141),('Althea Shaw',47,52),('Kyla Parrish',39,167);

